# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 865c1e7df1c5fb52b47860a567f0e1621edd6d89cfc63caf83059f05c438fdcf66c6487d7e15c11ef3993a6d35bd5b2b9eafc652872b7cb6e06aad97dd2a8a32

test:
  secret_key_base: 35a2ddd6f9e885a9d1a9298232ce570bfcdd0ba8598700bc7cd704f6b1ae04bd2a523a3b12ca0afab9943bc974a5180d8743cf510a05ccbb03e35efff621949b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
